.PHONY: handcrafted pytorch gpu

gpu:	
	env PYTHONPATH="$PYTHONPATH:$(pwd)"	python3 handcrafted/gpu/main.py

handcrafted:	
	env PYTHONPATH="$PYTHONPATH:$(pwd)"	python3 handcrafted/main.py

pytorch:
	env PYTHONPATH="$PYTHONPATH:$(pwd)"	python3 pytorch/main.py
